#!/usr/bin/python
#"""
#This game is written and created by Thomas Leichtfuss

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

#This program runs with python 2.6.4 and pygame.
#For Windows available at:
#http://www.python.org/ftp/python/2.6.4/python-2.6.4.msi
#http://pygame.org/ftp/pygame-1.9.1.win32-py2.6.msi
#"""

import os, sys, shutil

localsrc = os.path.join(os.getcwd(), 'Src')
if os.path.isdir(localsrc): CODEDIR = localsrc
else:
	if sys.platform == "win32":
		DATADIR = "C:\\Program Files\\kafkahoi"
		CODEDIR = "C:\\Program Files\\kafkahoi\\code"
	else:
		DATADIR = "/usr/local/share/games/kafkahoi"
		CODEDIR = "/usr/local/lib/games/kafkahoi"
	os.chdir(DATADIR)

sys.path.insert(0, CODEDIR)

from data import DATABASE, DB
if not os.stat(DB).st_uid == os.geteuid(): shutil.copyfile(DB, DATABASE)

from main import Main
if __name__=='__main__': Main()
